version: 1.0

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - restore_cache
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to latest cache if exact match not found
          - v1-dependencies-

      - run:
        name: Install dependencies
        command: yarn

      - run:
        name: Run tests
        command: yarn test

      - save_cache
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}